<?php


$lang['num_word_0']        = "";
$lang['num_word_1']        = 'واحد';
$lang['num_word_2']        = 'اثنين';
$lang['num_word_3']        = 'ثلاثة';
$lang['num_word_4']        = 'اربعة';
$lang['num_word_5']        = 'خمسة';
$lang['num_word_6']        = 'ستة';
$lang['num_word_7']        = 'سبعة';
$lang['num_word_8']        = 'ثمانية';
$lang['num_word_9']        = 'تسعة';
$lang['num_word_10']       = 'عشرة';
$lang['num_word_11']       = 'احدى عشر';
$lang['num_word_12']       = 'اثنى عشر';
$lang['num_word_13']       = 'ثلاثة عشر';
$lang['num_word_14']       = 'اربعة عشر';
$lang['num_word_15']       = 'خمسة عشر';
$lang['num_word_16']       = 'ستة عشر';
$lang['num_word_17']       = 'سبعة عشر';
$lang['num_word_18']       = 'ثمانية عشر';
$lang['num_word_19']       = 'تسعة عشر';
$lang['num_word_20']       = 'عشرون';
$lang['num_word_21']       = 'واحد وعشرون';
$lang['num_word_22']       = 'اثنان وعشرون';
$lang['num_word_23']       = 'ثلاثة وعشرون';
$lang['num_word_24']       = 'اربعة وعشرون';
$lang['num_word_25']       = 'خمسة وعشرون';
$lang['num_word_26']       = 'ستة وعشرون';
$lang['num_word_27']       = 'سبعة وعشرون';
$lang['num_word_28']       = 'ثمانية وعشرون';
$lang['num_word_29']       = 'تسعة وعشرون';
$lang['num_word_30']       = 'ثلاثون';
$lang['num_word_31']       = 'واحد وثلاثون';
$lang['num_word_32']       = 'اثنان وثلاثون';
$lang['num_word_33']       = 'ثلاثة وثلاثون';
$lang['num_word_34']       = 'ثلاثة واربعون';
$lang['num_word_35']       = 'خمسة وثلاثون';
$lang['num_word_36']       = 'ستة وثلاثون';
$lang['num_word_37']       = 'سبعة وثلاثون';
$lang['num_word_38']       = 'ثمانية وثلاثون';
$lang['num_word_39']       = 'تسعة وثلاثون';
$lang['num_word_40']       = 'اربعون';
$lang['num_word_41']       = 'واحد واربعون';
$lang['num_word_42']       = 'اثنان واربعون';
$lang['num_word_43']       = 'ثلاثة واربعون';
$lang['num_word_44']       = 'اربعة واربعون';
$lang['num_word_45']       = 'خمسة واربعون';
$lang['num_word_46']       = 'ستة واربعون';
$lang['num_word_47']       = 'سبعة واربعون';
$lang['num_word_48']       = 'ثمانية واربعون';
$lang['num_word_49']       = 'تسعة واربعون';
$lang['num_word_50']       = 'خمسون';
$lang['num_word_51']       = 'واحد وخمسون';
$lang['num_word_52']       = 'ٱثنين وخمسون';
$lang['num_word_53']       = 'ثلاثة وخمسون';
$lang['num_word_54']       = 'أربعة وخمسون';
$lang['num_word_55']       = 'خمسة وخمسون';
$lang['num_word_56']       = 'ستة وخمسون';
$lang['num_word_57']       = 'سبعة وخمسون';
$lang['num_word_58']       = 'ثمانية وخمسون';
$lang['num_word_59']       = 'تسعة وخمسون';
$lang['num_word_60']       = 'ستون';
$lang['num_word_61']       = 'واحد وستون';
$lang['num_word_62']       = 'ٱثنين وستون';
$lang['num_word_63']       = 'ثلاثة وستون';
$lang['num_word_64']       = 'أربعة وستون';
$lang['num_word_65']       = 'خمسة وستون';
$lang['num_word_66']       = 'ستة وستون';
$lang['num_word_67']       = 'سبعة وستون';
$lang['num_word_68']       = 'ثمانية وستون';
$lang['num_word_69']       = 'تسعة وستون';
$lang['num_word_70']       = 'سبعون';
$lang['num_word_71']       = 'واحد وسبعون';
$lang['num_word_72']       = 'اثنان وسبعون';
$lang['num_word_73']       = 'ثلاثة وسبعون';
$lang['num_word_74']       = 'أربعة وسبعون';
$lang['num_word_75']       = 'خمسة وسبعون';
$lang['num_word_76']       = 'ستة وسبعون';
$lang['num_word_77']       = 'سبعة وسبعون';
$lang['num_word_78']       = 'ثمانية وسبعون';
$lang['num_word_79']       = 'تسعة وسبعون';
$lang['num_word_80']       = 'ثمانون';
$lang['num_word_81']       = 'واحد وثمانون';
$lang['num_word_82']       = 'اثنان وثمانون';
$lang['num_word_83']       = 'ثلاثة وثمانون';
$lang['num_word_84']       = 'أربعة وثمانون';
$lang['num_word_85']       = 'خمسة وثمانون';
$lang['num_word_86']       = 'ستة وثمانون';
$lang['num_word_87']       = ' سبعة وثمانون';
$lang['num_word_88']       = 'ثمانية وثمانون';
$lang['num_word_89']       = 'تسعة وثمانون';
$lang['num_word_90']       = 'تسعون';
$lang['num_word_91']       = 'واحد وتسعون';
$lang['num_word_92']       = 'ٱثنين وتسعون';
$lang['num_word_93']       = 'ثلاثة وتسعون';
$lang['num_word_94']       = 'أربعة وتسعون';
$lang['num_word_95']       = 'خمسة وتسعون';
$lang['num_word_96']       = 'ستة وتسعون';
$lang['num_word_97']       = 'سبعة وتسعون';
$lang['num_word_98']       = 'ثمانية وتسعون';
$lang['num_word_99']       = 'تسعة وتسعون';
$lang['num_word_100']      = 'مائة';
$lang['num_word_200']      = 'مائتين';
$lang['num_word_300']      = 'ثلاثمائه';
$lang['num_word_400']      = 'اربعمائة';
$lang['num_word_500']      = 'خمسمائة';
$lang['num_word_600']      = 'ستمائة';
$lang['num_word_700']      = 'سبعمائة';
$lang['num_word_800']      = 'ثمانمائة ';
$lang['num_word_900']      = 'تسعمائة';
$lang['num_word_thousand'] = 'الف';
$lang['num_word_million']  = 'مليون';
$lang['num_word_billion']  = 'مليار';
$lang['num_word_trillion'] = 'ترليون';
$lang['num_word_zillion']  = 'زليون';
$lang['num_word_cents']    = 'سنت';
$lang['number_word_and']   = 'و';

// Show in invoices and estimates
$lang['num_word'] = 'كتابةً';

$currencies = [
    'USD' => 'دولار',
    'SAR' => 'ريال',
    'SDG' => 'جنيه سوداني',
    'EUR' => 'يورو'
];

$currencies = hooks()->apply_filters('before_number_format_render_languge_currencies', $currencies);

foreach ($currencies as $key => $val) {

        $lang['num_word_' . strtoupper($key)] = $val;
}
